# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mke/Dropbox/Psc_Build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mke/Dropbox/Psc_Build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mke/Dropbox/Psc_Build/CMakeFiles /Users/mke/Dropbox/Psc_Build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mke/Dropbox/Psc_Build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/mke/Dropbox/Psc_Build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pscal

# Build rule for target.
pscal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pscal
.PHONY : pscal

# fast build rule for target.
pscal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/build
.PHONY : pscal/fast

#=============================================================================
# Target rules for targets named dscal

# Build rule for target.
dscal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dscal
.PHONY : dscal

# fast build rule for target.
dscal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/build
.PHONY : dscal/fast

#=============================================================================
# Target rules for targets named hscal

# Build rule for target.
hscal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hscal
.PHONY : hscal

# fast build rule for target.
hscal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/build
.PHONY : hscal/fast

src/ast.o: src/ast.c.o
.PHONY : src/ast.o

# target to build an object file
src/ast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/ast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/ast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/ast.c.o
.PHONY : src/ast.c.o

src/ast.i: src/ast.c.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/ast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/ast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/ast.c.i
.PHONY : src/ast.c.i

src/ast.s: src/ast.c.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/ast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/ast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/ast.c.s
.PHONY : src/ast.c.s

src/builtin.o: src/builtin.c.o
.PHONY : src/builtin.o

# target to build an object file
src/builtin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin.c.o
.PHONY : src/builtin.c.o

src/builtin.i: src/builtin.c.i
.PHONY : src/builtin.i

# target to preprocess a source file
src/builtin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin.c.i
.PHONY : src/builtin.c.i

src/builtin.s: src/builtin.c.s
.PHONY : src/builtin.s

# target to generate assembly for a file
src/builtin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin.c.s
.PHONY : src/builtin.c.s

src/builtin_network_api.o: src/builtin_network_api.c.o
.PHONY : src/builtin_network_api.o

# target to build an object file
src/builtin_network_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin_network_api.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin_network_api.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin_network_api.c.o
.PHONY : src/builtin_network_api.c.o

src/builtin_network_api.i: src/builtin_network_api.c.i
.PHONY : src/builtin_network_api.i

# target to preprocess a source file
src/builtin_network_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin_network_api.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin_network_api.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin_network_api.c.i
.PHONY : src/builtin_network_api.c.i

src/builtin_network_api.s: src/builtin_network_api.c.s
.PHONY : src/builtin_network_api.s

# target to generate assembly for a file
src/builtin_network_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/builtin_network_api.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/builtin_network_api.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/builtin_network_api.c.s
.PHONY : src/builtin_network_api.c.s

src/globals.o: src/globals.c.o
.PHONY : src/globals.o

# target to build an object file
src/globals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/globals.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/globals.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/globals.c.o
.PHONY : src/globals.c.o

src/globals.i: src/globals.c.i
.PHONY : src/globals.i

# target to preprocess a source file
src/globals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/globals.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/globals.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/globals.c.i
.PHONY : src/globals.c.i

src/globals.s: src/globals.c.s
.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/globals.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/globals.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/globals.c.s
.PHONY : src/globals.c.s

src/interpreter.o: src/interpreter.c.o
.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/interpreter.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/interpreter.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/interpreter.c.o
.PHONY : src/interpreter.c.o

src/interpreter.i: src/interpreter.c.i
.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/interpreter.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/interpreter.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/interpreter.c.i
.PHONY : src/interpreter.c.i

src/interpreter.s: src/interpreter.c.s
.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/interpreter.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/interpreter.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/interpreter.c.s
.PHONY : src/interpreter.c.s

src/lexer.o: src/lexer.c.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/lexer.c.o
.PHONY : src/lexer.c.o

src/lexer.i: src/lexer.c.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/lexer.c.i
.PHONY : src/lexer.c.i

src/lexer.s: src/lexer.c.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/lexer.c.s
.PHONY : src/lexer.c.s

src/list.o: src/list.c.o
.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/list.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/list.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i
.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/list.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/list.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s
.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/list.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/list.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/symbol.o: src/symbol.c.o
.PHONY : src/symbol.o

# target to build an object file
src/symbol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/symbol.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/symbol.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/symbol.c.o
.PHONY : src/symbol.c.o

src/symbol.i: src/symbol.c.i
.PHONY : src/symbol.i

# target to preprocess a source file
src/symbol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/symbol.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/symbol.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/symbol.c.i
.PHONY : src/symbol.c.i

src/symbol.s: src/symbol.c.s
.PHONY : src/symbol.s

# target to generate assembly for a file
src/symbol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/symbol.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/symbol.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/symbol.c.s
.PHONY : src/symbol.c.s

src/types.o: src/types.c.o
.PHONY : src/types.o

# target to build an object file
src/types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/types.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/types.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/types.c.o
.PHONY : src/types.c.o

src/types.i: src/types.c.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/types.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/types.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/types.c.i
.PHONY : src/types.c.i

src/types.s: src/types.c.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/types.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/types.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/types.c.s
.PHONY : src/types.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pscal.dir/build.make CMakeFiles/pscal.dir/src/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dscal.dir/build.make CMakeFiles/dscal.dir/src/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hscal.dir/build.make CMakeFiles/hscal.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... dscal"
	@echo "... hscal"
	@echo "... pscal"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/builtin.o"
	@echo "... src/builtin.i"
	@echo "... src/builtin.s"
	@echo "... src/builtin_network_api.o"
	@echo "... src/builtin_network_api.i"
	@echo "... src/builtin_network_api.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/symbol.o"
	@echo "... src/symbol.i"
	@echo "... src/symbol.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/mke/Dropbox/Psc_Build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

