#!/bin/sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CURL_SRC="$ROOT/third-party/curl-8.17.0"
BUILD_DIR="$ROOT/build/curl-ios"
INSTALL_DIR="$ROOT/build/curl-ios-install"
ARCHS="${ARCHS:-arm64}"

if [ -z "${OPENSSL_ROOT_DIR:-}" ]; then
  cat >&2 <<'EOF'
OPENSSL_ROOT_DIR must point at an iOS-capable OpenSSL install (for example,
the prefix generated by the CMake ios-device/ios-simulator presets). Without
it, libcurl will be built without TLS support.
EOF
  exit 1
fi

rm -rf "$BUILD_DIR" "$INSTALL_DIR"
mkdir -p "$BUILD_DIR" "$INSTALL_DIR"

cmake -S "$CURL_SRC" -B "$BUILD_DIR" \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0 \
  -DCMAKE_OSX_ARCHITECTURES="${ARCHS}" \
  -DOPENSSL_ROOT_DIR="${OPENSSL_ROOT_DIR}" \
  -DUSE_APPLE_SECTRUST=ON \
  -DCURL_USE_OPENSSL=ON \
  -DCURL_USE_LIBPSL=OFF \
  -DUSE_LIBPSL=OFF \
  -DCURL_ZSTD=OFF \
  -DCURL_BROTLI=OFF \
  -DUSE_NGHTTP2=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DBUILD_CURL_EXE=OFF \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
  -DCURL_DISABLE_LDAP=ON \
  -DHTTP_ONLY=ON \
  -DBUILD_TESTING=OFF

cmake --build "$BUILD_DIR" --config Release --parallel
cmake --install "$BUILD_DIR" --config Release
