PASCAL_BIN ?= ../build/bin/pascal

.PHONY: help threads-procptr-demo

help:
	@echo "Available example targets:"
	@echo "  make threads-procptr-demo  # Run ThreadsProcPtrDemo (procedure pointers + threads)"
	@echo "Variables:"
	@echo "  PASCAL_BIN=$(PASCAL_BIN)"

threads-procptr-demo:
	@echo "Running ThreadsProcPtrDemo..."
        @$(PASCAL_BIN) pascal/base/ThreadsProcPtrDemo

