name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libcurl4-openssl-dev
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: CTest
        run: cd build && ctest --output-on-failure
      - name: Run CLike tests
        run: Tests/run_clike_tests.sh
      - name: Run Shell tests
        run: Tests/run_shell_tests.sh
      - name: Run Pascal tests
        run: Tests/run_pascal_tests.sh
      - name: Run Rea tests
        env:
          REA_SKIP_TESTS: "constructor_init field_access_assign field_access_read method_this_assign new_alloc new_assign_ptr"
        run: Tests/run_rea_tests.sh
      - name: Run CLike scope tests
        run: python3 Tests/scope_verify/clike/clike_scope_test_harness.py --manifest Tests/scope_verify/clike/tests/manifest.json
      - name: Run Pascal scope tests
        run: python3 Tests/scope_verify/pascal/pascal_scope_test_harness.py --manifest Tests/scope_verify/pascal/tests/manifest.json
      - name: Run Rea scope tests
        run: python3 Tests/scope_verify/rea/rea_scope_test_harness.py --manifest Tests/scope_verify/rea/tests/manifest.json
      - name: Compile CLike examples (dump-only)
        run: |
          set -e
          export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy
          export CLIKE_LIB_DIR="$GITHUB_WORKSPACE/Examples/clike"
          for f in Examples/clike/*; do
            bn=$(basename "$f");
            case "$bn" in README.md|builtins.h|mbt.save|typescript) continue;; esac
            if [ -f "$f" ]; then
              echo "CLike example: $bn"
              build/bin/clike --dump-bytecode-only "$f" >/dev/null
            fi
          done
      - name: Compile Shell examples (dump-only)
        run: |
          set -e
          for f in Examples/psh/*.psh; do
            if [ -f "$f" ]; then
              bn=$(basename "$f")
              echo "Shell example: $bn"
              build/bin/psh --dump-bytecode-only "$f" >/dev/null
            fi
          done
      - name: Compile Pascal examples (dump-only)
        run: |
          set -e
          export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy
          export PASCAL_LIB_DIR="$GITHUB_WORKSPACE/lib/pascal"
          SDL_ENABLED=$(grep -q '^SDL:BOOL=ON$' build/CMakeCache.txt && echo 1 || echo 0)
          for f in Examples/Pascal/*; do
            bn=$(basename "$f")
            if [ -f "$f" ]; then
              # Skip SDL-dependent examples when SDL is not enabled in the build
              if [ "$SDL_ENABLED" -ne 1 ]; then
                # Heuristic: skip if the name suggests SDL, or if the file references SDL graphics/sound builtins
                if echo "$bn" | grep -qiE '(^SDL|SDL|mandoSDL)'; then
                  echo "Skipping SDL example (SDL disabled): $bn"
                  continue
                fi
                if grep -qiE '(initsoundsystem|loadsound|playsound|issoundplaying|freesound|quitsoundsystem|initgraph|closegraph|updatescreen|rendercopyex|outtextxy|setrgbcolor|drawline|fillrect|fillcircle|inittextsystem|graphloop|createtexture|destroytexture|updatetexture)' "$f"; then
                  echo "Skipping SDL-dependent example (SDL disabled): $bn"
                  continue
                fi
              fi
              echo "Pascal example: $bn"
              build/bin/pascal --dump-bytecode-only "$f" >/dev/null
            fi
          done
      - name: Compile Rea examples (dump-only)
        run: |
          set -e
          export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy
          export REA_LIB_DIR="$GITHUB_WORKSPACE/lib/rea"
          export PASCAL_LIB_DIR="$GITHUB_WORKSPACE/lib/pascal"
          SDL_ENABLED=$(grep -q '^SDL:BOOL=ON$' build/CMakeCache.txt && echo 1 || echo 0)
          for f in Examples/rea/*.rea; do
            bn=$(basename "$f")
            if [ -f "$f" ]; then
              # Skip SDL-dependent examples when SDL is not enabled in the build
              if [ "$SDL_ENABLED" -ne 1 ]; then
                if echo "$bn" | grep -qiE '^sdl'; then
                  echo "Skipping SDL example (SDL disabled): $bn"
                  continue
                fi
              fi
              echo "Rea example: $bn"
              build/bin/rea --dump-bytecode-only "$f" >/dev/null
            fi
          done
